### ISSUE TITLE
大佬新年快乐请问一下有qq交流群吗，

### ISSUE THREAD

**Issue by yueGG666** [li1055107552/xiaoe-tech-decodeDemo#3]

**Comment by li1055107552** [comment]
没有哦，暂时也没这个打算

**Comment by yueGG666** [comment]
看不懂这个教程呀高三党学生看不懂😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 中午12:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [li1055107552/xiaoe-tech-decodeDemo] 大佬新年快乐请问一下有qq交流群吗， (Issue #3)




 
没有哦，暂时也没这个打算
