### ISSUE TITLE
大佬好，麻烦问下有遇到下边2个报错么？

### ISSUE THREAD

**Issue by chenguangliang** [li1055107552/xiaoe-tech-decodeDemo#5]
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

跑一次能成功几个文件，然后就失败，出现上边的错之一。
多谢大佬啦！

**Comment by li1055107552** [comment]
解密错误，长度不正确，可能是存在以下几种情况：
1. 文件本身不需要解密，直接合并就好。这种情况建议直接使用隔壁的插件 [猫爪 cat-catch](https://github.com/xifangczy/cat-catch)
2. 文件的加密方式不是 `aes-128-cbc` ，这个可以查看 .m3u8 文件
3. 得到的密钥 不是真正解密的密钥（这个我也没有什么好的办法，只能看他用什么解密的，要么就是密钥的地址不正确）
4. node版本或环境问题

**Comment by chenguangliang** [comment]
删除下载目录，重新跑一遍就好了，感谢大佬！
